GithubPullTracker/Controllers/PullRequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using GithubPullTracker.Models;
using System.Net.Http;
using System.Text.RegularExpressions;
using System.IO;
using System.Text;
using System.Net;
using AttributeRouting.Web.Mvc;
using GithubPullTracker.DataStore;
using System.Security.Cryptography;
using GithubClient.Models;

namespace GithubPullTracker.Controllers
{
    public class PullRequestController : ControllerBase
    {

        private async Task<PullRequestView> GetPullRequestDetails(string owner, string repo, int number)
        {

            var store = new RepoStore();
            var prTask = Client.PullRequest(owner, repo, number);
            
            var assignees = Client.Assignees(owner, repo, number);
            var approvalsTask = store.GetApprovals(owner, repo, number);
            var repoSettingsTask = store.GetOwnerConfig(owner, repo);
            await Task.WhenAll(prTask,  assignees, approvalsTask, repoSettingsTask);

            return new PullRequestView(CurrentUser, prTask.Result, assignees.Result, approvalsTask.Result, repoSettingsTask.Result);
        }
        [Auth]
        [POST("{owner}/{repo}/pull/{reference}/approve")]
        public async Task<ActionResult> Approve(string owner, string repo, int reference, string headSha, bool approved, string path = null)
        {
            Store.UpdateApproval(owner, repo, reference, headSha, CurrentUser.UserName, approved);
            await Store.Flush();

            var pullRequest= await GetPullRequestDetails(owner, repo, reference);

            var reposettings = await Store.GetRepoSettings(owner, repo);

            var privateenabled = reposettings.PrivateEnabled;
            var publicenabled = reposettings.PublicEnabled && !pullRequest.IsPrivate;
            if (publicenabled || privateenabled)//no enabled eather way
            {
                if (pullRequest.IsPrivate)
                {
                    //getorg settings
                    var ownerSettings = await Store.GetOwnerSettings(owner);
                    if (ownerSettings.SubscriptionExpires <= DateTime.UtcNow)
                    {
                        return RedirectToAction("ViewPullRequest", new { owner, repo, reference, error="subscriptionexpired" });
                    }
                }

                var ownerClient = new GithubClient.Client(Client.UserAgent) { AccessToken = reposettings.GetAuthToken() };

                var settings = await Store.GetPullRequestSettings(owner, repo, reference);

                var statuslist= await ownerClient.GetStatuses(owner, repo, headSha);

                var details = pullRequest;
                settings.Approved = details.ExpectedStatus == CommitStatus.success;

                var currentstatus = statuslist.statuses.Where(x => x.context == RepositoryController.statuscontext).SingleOrDefault();
                var status = currentstatus?.state ?? CommitStatus.error;
                var description = currentstatus?.description;

                if (status != details.ExpectedStatus || description != details.StatusDescription)
                {

                    var url = Request.Url.GetLeftPart(UriPartial.Authority) + $"/{owner}/{repo}/pull/{reference}";
                    //we could enque this update for a background task to complete???
                    await ownerClient.SetStatus(owner, repo, headSha, details.ExpectedStatus, url, details.StatusDescription, RepositoryController.statuscontext);
                }

                //all now approved

                Store.UpdatePullRequestSettings(settings);
                await Store.Flush();
            }

            if (path == null) {
                return RedirectToAction("ViewPullRequest", new { owner, repo, reference });
            }else
            {
                return RedirectToAction("ViewFiles", new { owner, repo, reference, path = path });
            }
        }

        [Auth]
        [GET("{owner}/{repo}/pull/{reference}")]
        public async Task<ActionResult> ViewPullRequest(string owner, string repo, int reference)
        {
            var pullRequestTask = GetPullRequestDetails(owner, repo, reference);

            var issueTask = Client.Issue(owner, repo, reference);
            
            var commentsTask =  Client.FileComments(owner, repo, reference);            
            
            var timelineTask =  Client.Timeline(owner, repo, reference);

            var issueCommentsTask = Client.Comments(owner, repo, reference);
            var commitsTask = Client.Commits(owner, repo, reference);
            await Task.WhenAll(pullRequestTask, issueTask, commentsTask, timelineTask, issueCommentsTask, commitsTask);

            var pr = new PullRequestCommentsView(pullRequestTask.Result, issueTask.Result, commentsTask.Result, timelineTask.Result, issueCommentsTask.Result, commitsTask.Result);
            return View(pr);
        }

        [GET("{owner}/{repo}/pull/{reference}/files/{*path}")]
        public async Task<ActionResult> ViewFiles(string owner, string repo, int reference, string path = null, string sha = null, string filesha = null)
        {
            var repoStore = new RepoStore();
            if (Request.IsAjaxRequest())
            {


                string sourceText = "";
                bool fileMissing = false;
                bool isBinaryDataType = false;
                try
                {
                    var sourceFile = await Client.FileContents(owner, repo, path, sha);
                    if (sourceFile != null)
                    {
                        if (sourceFile.encoding == "base64")
                        {
                            var data = Convert.FromBase64String(sourceFile.content);

                            sourceText = readData(data, out isBinaryDataType);
                        }

                    }
                }
                catch (Exception ex)
                {
                    fileMissing = true;
                }

                if (!string.IsNullOrEmpty(filesha))
                {
                    repoStore.AddFileView(owner, repo, reference, filesha, CurrentUser.UserName);
                }
                var json = Newtonsoft.Json.JsonConvert.SerializeObject(new
                {
                    contents = sourceText,
                    isBinary = isBinaryDataType,
                    missing = fileMissing,
                });

                await repoStore.Flush();

                return Content(json, "application/json");
            }

            var files = await Client.Files(owner, repo, reference);

            if (path == null)
            {
                path = files.First().filename;
                return RedirectToAction("ViewFiles", new { owner, repo, reference, path });
            }
            else
            {

                var pullRequest = await GetPullRequestDetails(owner, repo, reference);

                path = path.TrimEnd('/');

                var file = files.Where(x => x.filename == path).Single();

                repoStore.AddFileView(owner, repo, reference, file.sha, CurrentUser.UserName);

                string sourceText = "";
                bool isBinaryDataType = false;

                try
                {
                    if (file.status != "removed")
                    {
                        var sourceFile = await Client.FileContents(owner, repo, path, pullRequest.HeadSha);
                        if (sourceFile != null)
                        {
                            if (sourceFile.encoding == "base64")
                            {
                                var data = Convert.FromBase64String(sourceFile.content);

                                sourceText = readData(data, out isBinaryDataType);
                            }
                        }
                    }
                }
                catch (Exception ex)
                {
                }
                var visistedFiles = await repoStore.ListFileViews(owner, repo, reference, CurrentUser.UserName);

                var comments = await Client.FileComments(owner, repo, reference);
                var vm = new PullRequestFileView(pullRequest, files, path, sourceText, isBinaryDataType, comments, visistedFiles);


                return View(vm);
            }
        }

        public static string readData(byte[] data, out bool isBinary)
        {
            isBinary = false;
            long length = data.Length;
            if (length == 0) return "";

            StringBuilder sb = new StringBuilder();
            using (StreamReader stream = new StreamReader(new MemoryStream(data)))
            {
                int ch;
                while ((ch = stream.Read()) != -1)
                {
                    if (isControlChar(ch))
                    {
                        isBinary = true;
                        return "";
                    }
                    sb.Append((char)ch);
                }
            }
            return sb.ToString();
        }

        public static bool isControlChar(int ch)
        {
            return (ch > Chars.NUL && ch < Chars.BS)
                || (ch > Chars.CR && ch < Chars.SUB);
        }

        public static class Chars
        {
            public static char NUL = (char)0; // Null char
            public static char BS = (char)8; // Back Space
            public static char CR = (char)13; // Carriage Return
            public static char SUB = (char)26; // Substitute
        }
    }
}

GithubPullTracker/Views/Repository/SearchRepo.cshtml
@model GithubPullTracker.Models.RepoSearchResults

@{
    var CurrentUser = ViewData["__CurrentUser__"] as GithubUser;

    string state = (Model.State == GithubClient.RequestState.Open ? $"{Model.OpenHits} open" : $"{Model.ClosedHits} closed");
    string connection = "";
    switch (Model.ConnectionType)
    {
        case GithubClient.RequestConnection.Assigned:
            connection = $" · Assigned to {CurrentUser.UserName}";
            break;
        case GithubClient.RequestConnection.Involved:
            connection = $" · Involving {CurrentUser.UserName}";
            break;
        case GithubClient.RequestConnection.Author:
            connection = $" · Created by {CurrentUser.UserName}";
            break;
        case GithubClient.RequestConnection.All:
        default:
            break;
    }

    ViewBag.Title = $"{Model.Repo.owner.login}/{Model.Repo.name} · Pull Requests · {state}{connection}";
}


<div class="header-content">
    <div class="container ">
        <div class="title-bar">
            @if (Model.IsAdmin)
            {
                <a class="config" href="~/@Model.Repo.owner.login/@Model.Repo.name/settings" title="settings"><i class="icon icon-gear"></i><span>Settings</span></a>
            }
            <h1><i class="icon icon-repo"></i><a class="owner" href="~/@Model.Repo.owner.login">@Model.Repo.owner.login</a> / <a class="repo" href="~/@Model.Repo.owner.login/@Model.Repo.name">@Model.Repo.name</a></h1>

        </div>
    </div>
</div>
<div class="homepage">
    <div id="searchResults" class="noRepos">


        <div class='header'>
            <div class="left">
                <a href="@Model.GenerateStateUrl(GithubClient.RequestState.Open)" class="@(Model.State == GithubClient.RequestState.Open?"selected" : null)">
                    <i class="icon icon-git-pull-request"></i>
                    <span>@Model.OpenHits</span>
                    Open
                </a>
                <a href="@Model.GenerateStateUrl(GithubClient.RequestState.Closed)" class="@(Model.State == GithubClient.RequestState.Closed?"selected" : null)">
                    <i class="icon icon-check"></i>
                    <span>@Model.ClosedHits</span>
                    Closed
                </a>
            </div>
            <div class="right">
                <a href="@Model.GenerateConnectionUrl(GithubClient.RequestConnection.All)" class="@(Model.ConnectionType == GithubClient.RequestConnection.All?"selected" : null)">All</a>
                <a href="@Model.GenerateConnectionUrl(GithubClient.RequestConnection.Assigned)" class="@(Model.ConnectionType == GithubClient.RequestConnection.Assigned?"selected" : null)">Assigned</a>
                <a href="@Model.GenerateConnectionUrl(GithubClient.RequestConnection.Author)" class="@(Model.ConnectionType == GithubClient.RequestConnection.Author?"selected" : null)">Created</a>
                <a href="@Model.GenerateConnectionUrl(GithubClient.RequestConnection.Involved)" class="@(Model.ConnectionType == GithubClient.RequestConnection.Involved?"selected" : null)">Involved</a>
            </div>
        </div>
        <div class="rows">
            @foreach (var result in Model.Items)
            {
                <div class="@(result.ClosedAt.HasValue ? "closed" : null)">
                    <div class="title">
                        <i class="icon icon-git-pull-request"></i>


                        <a class="pull" href="@Url.Action("ViewPullRequest", "PullRequest", new { owner = result.RepositoryOwner, repo = result.RepositoryName, reference = result.Number })">
                            @result.Title
                        </a>
                        @foreach (var l in result.Labels)
                        {
                            <span class="label" style="background-color:#@l.color">@l.name</span>
                        }@if (result.Assignee != null)
                        {
                            <a class="user" target="_blank" href="@result.Assignee.html_url"><img alt="@result.Assignee.login" src="@(result.Assignee.avatar_url)&s=40"></a>
                        }
                    </div>
                    <div class="meta">
                        #@(result.Number)
                        @if (result.ClosedAt.HasValue)
                {
                            <text> by
                                <a href="@result.CreateBy.html_url" target="_blank">@result.CreateBy.login</a>
                                was closed <time class="timeago" datetime="@result.CreatedAt.ToString("o")">@result.CreatedAt.ToString()</time>
                            </text>
                        }
                        else
                        {
                            <text>
                                opened
                                <time class="timeago" datetime="@result.CreatedAt.ToString("o")">@result.CreatedAt.ToString()</time> by
                                <a href="@result.CreateBy.html_url" target="_blank">@result.CreateBy.login</a>
                            </text>
                        }
                    </div>
                </div>
            }
        </div>
        @if (Model.PageCount > 1)
        {
            //sectinos top draw

            List<int> pages = new List<int>();

            pages.Add(1);
            pages.Add(2);
            pages.Add(3);

            pages.Add(Model.Page - 3);
            pages.Add(Model.Page - 2);
            pages.Add(Model.Page - 1);
            pages.Add(Model.Page);
            pages.Add(Model.Page + 1);
            pages.Add(Model.Page + 2);
            pages.Add(Model.Page + 3);

            pages.Add(Model.PageCount - 1);
            pages.Add(Model.PageCount);
            pages = pages.Where(x => x >= 1 && x <= Model.PageCount).Distinct().ToList();

            <div class="pagination">
                <nav>
                    @if (Model.Page > 1)
                {
                        <a href="@Model.GeneratePageUrl(Model.Page -1)">Previous</a>
                    }
                    else
                    {
                        <span>Previous</span>
                    }
                    @for (var i = 0; i < pages.Count; i++)
                    {
                        if (i > 0 && pages[i - 1] + 1 != pages[i])
                        {
                            //we skeipped some
                            <span>&hellip;</span>
                        }
                        <a href="@Model.GeneratePageUrl(pages[i])" class="@(pages[i] == Model.Page ? "selected" : null)">@pages[i]</a>
                    }
                    @if (Model.Page < Model.PageCount)
                {
                        <a href="@Model.GeneratePageUrl(Model.Page +1)">Next</a>
                    }
                    else
                    {
                        <span>Next</span>}
                </nav>
            </div>
        }
    </div>

</div>

GithubPullTracker/Views/Repository/Settings.cshtml
@model RepoSettingsViewModel

@{
    ViewBag.Title = "Settings";
}
<div class="header-content">
    <div class="container ">
        <div class="title-bar">

            <h1><i class="icon icon-repo"></i><a class="owner" href="~/@Model.RepoOwner">@Model.RepoOwner</a> / <a class="repo" href="~/@Model.RepoOwner/@Model.RepoName">@Model.RepoName</a></h1>

        </div>
    </div>
</div>
<div class="homepage">
    <div class="panel">
        <h2>Approval tracking</h2>
        @if (Model.WebhookMissConfigured)
        {
            <p class="alert warning">
                We have detected the webhook intergration with github is missconfigured.
            </p>
            <form class="action" action="@Url.Action("Configure")" method="post">
                <input type="hidden" name="enabled" value="@(Model.Enabled.ToString())" />
                <button type="submit">Fix</button>
            </form>
        }
        else
        {
            <p>Track pull request approvals for this repository.</p>
            if (Model.CanConfigure)
            {
                <form class="action" action="@Url.Action("Configure")" method="post">
                    <input type="hidden" name="enabled" value="@((!Model.Enabled).ToString())" />
                    @if (Model.Enabled)
                    {
                        <button type="submit" class="danger">Remove Tracking</button>
                    }
                    else
                    { <button type="submit">Track</button>}
                </form>
            }
            else
            {
                <div class="action">
                    we're sorry but you can't enable tracking on this repository.
                </div>
            }
        }
    </div>
    <div class="panel">
        <h2>Branch Protection</h2>

        <p>TODO show/update branch protection in here</p>
    </div>
</div>